export const GALLERY_CATEGORIES = [
  { id: 'academia', label: 'Academia / Fitness', icon: '💪', group: 'Esportes' },
  { id: 'acompanhamento', label: 'Acompanhamento Mensal', icon: '🗓️', group: 'Família' },
  { id: 'alimentos', label: 'Alimentos / Gastronomia', icon: '🍕', group: 'Comercial' },
  { id: 'aniversario-adulto', label: 'Aniversário Adulto', icon: '🎂', group: 'Social' },
  { id: 'aniversario-infantil', label: 'Aniversário Infantil', icon: '🎈', group: 'Social' },
  { id: 'automobilismo', label: 'Auto / Track Day', icon: '🏎️', group: 'Automotivo' },
  { id: 'balada', label: 'Balada / Nightlife', icon: '🎧', group: 'Entretenimento' },
  { id: 'batizado', label: 'Batizado / Consagração', icon: '🕊️', group: 'Social' },
  { id: 'bodas', label: 'Bodas / Renovação', icon: '🥂', group: 'Social' },
  { id: 'boudoir', label: 'Boudoir / Sensual', icon: '🌹', group: 'Ensaios' },
  { id: 'casamento', label: 'Casamento / Wedding', icon: '💍', group: 'Social' },
  { id: 'corporativo', label: 'Corporativo / Palestras', icon: '🏢', group: 'Comercial' },
  { id: 'cosplay', label: 'Cosplay / Artístico', icon: '🎨', group: 'Ensaios' },
  { id: 'danca', label: 'Dança / Ballet', icon: '🩰', group: 'Entretenimento' },
  { id: 'quinze-anos', label: 'Debutante / 15 Anos', icon: '💃', group: 'Social' },
  { id: 'ensaio-feminino', label: 'Ensaio Feminino', icon: '👸', group: 'Ensaios' },
  { id: 'ensaio-masculino', label: 'Ensaio Masculino', icon: '🤵', group: 'Ensaios' },
  { id: 'esporte-aventura', label: 'Esporte de Aventura', icon: '🧗', group: 'Esportes' },
  { id: 'especialidades', label: 'Especialidades / Outros', icon: '✨', group: 'Geral' },
  { id: 'familia', label: 'Família / Lifestyle', icon: '🏠', group: 'Família' },
  { id: 'festa-tematica', label: 'Festa Temática', icon: '🎭', group: 'Social' },
  { id: 'festival', label: 'Festival / Grandes Eventos', icon: '🎪', group: 'Entretenimento' },
  { id: 'formatura', label: 'Formatura / Colação', icon: '🎓', group: 'Social' },
  { id: 'futebol', label: 'Futebol / Esportes Coletivos', icon: '⚽', group: 'Esportes' },
  { id: 'gastronomia', label: 'Gastronomia / Culinária', icon: '🍽️', group: 'Comercial' },
  { id: 'gestante', label: 'Gestante / Doce Espera', icon: '🤰', group: 'Família' },
  { id: 'hipismo', label: 'Hipismo / Cavalos', icon: '🐎', group: 'Esportes' },
  { id: 'imobiliario', label: 'Imobiliário / Arquitetura', icon: '🏠', group: 'Comercial' },
  { id: 'institucional', label: 'Institucional / Equipe', icon: '👨‍💼', group: 'Comercial' },
  { id: 'interiores', label: 'Interiores / Design', icon: '🛋️', group: 'Comercial' },
  { id: 'joias', label: 'Joias / Still', icon: '💎', group: 'Comercial' },
  { id: 'lifestyle', label: 'Lifestyle / Casual', icon: '🏡', group: 'Família' },
  { id: 'macro', label: 'Macro / Detalhes', icon: '🔍', group: 'Natureza' },
  { id: 'moda', label: 'Moda / Editorial', icon: '👗', group: 'Ensaios' },
  { id: 'motociclismo', label: 'Motociclismo', icon: '🏍️', group: 'Automotivo' },
  { id: 'natureza', label: 'Natureza / Paisagem', icon: '🌿', group: 'Natureza' },
  { id: 'newborn', label: 'Newborn / Recém-Nascido', icon: '👶', group: 'Família' },
  { id: 'perfil-profissional', label: 'Perfil Profissional', icon: '💼', group: 'Ensaios' },
  { id: 'pet', label: 'Pet / Animais', icon: '🐾', group: 'Natureza' },
  { id: 'pre-wedding', label: 'Pré-Wedding', icon: '👩‍❤️‍👨', group: 'Social' },
  { id: 'produto', label: 'Produto / E-commerce', icon: '📦', group: 'Comercial' },
  { id: 'publicidade', label: 'Publicidade / Campanhas', icon: '📢', group: 'Comercial' },
  { id: 'religioso', label: 'Religioso / Cultos', icon: '⛪', group: 'Social' },
  { id: 'show', label: 'Show / Concerto', icon: '🎸', group: 'Entretenimento' },
  { id: 'skate', label: 'Skate / Street', icon: '🛹', group: 'Esportes' },
  { id: 'smash-the-cake', label: 'Smash the Cake', icon: '🍰', group: 'Família' },
  { id: 'street-photography', label: 'Street Photography', icon: '🏙️', group: 'Natureza' },
  { id: 'surf', label: 'Surf / Praia', icon: '🏄', group: 'Esportes' },
  { id: 'teatro', label: 'Teatro / Espetáculo', icon: '🎬', group: 'Entretenimento' },
  { id: 'viagem', label: 'Viagem / Turismo', icon: '✈️', group: 'Natureza' },
] as const;